import Head from 'next/head'
import Hero from "./../components/sections/hero.js"

export default function Home() {
  return (
    <>
        <Head>
        <title>Amit Jhariya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>

            
    </>
  )
}
