import Hero from './components/sections/hero.js'

export default function Page() {
  return (
    <>
        <head>
        <title>Amit Jhariya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Hero/>            
    </>
  )
}
